import type { Metadata } from "next";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import { Source_Sans_3 } from "next/font/google";
import ReactQueryProvider from "./ReactQueryProvider";

import "swiper/css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sourceSans3 = Source_Sans_3({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sourceSans3.className} antialiased`}>
        <ReactQueryProvider>
          <Header />
          <main className="pt-safe">{children}</main>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
